# Generated by Django 3.2.4 on 2021-06-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
    ]
